//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAPWT.MODEL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MASAC_SEIDOREntities : DbContext
    {
        public MASAC_SEIDOREntities()
            : base("name=MASAC_SEIDOREntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<IGN1> IGN1 { get; set; }
        public virtual DbSet<OIGN> OIGN { get; set; }
        public virtual DbSet<OWTR> OWTR { get; set; }
        public virtual DbSet<WTR1> WTR1 { get; set; }
    }
}
